//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPMSapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ground_facility
    {
        public int id { get; set; }
        public Nullable<int> gid { get; set; }
        public Nullable<int> fid { get; set; }
    
        public virtual facility facility { get; set; }
        public virtual ground ground { get; set; }
    }
}
